### ISSUE TITLE
yii2-sypexdumper

### ISSUE THREAD

**Issue by loveorigami** [Beaten-Sect0r/yii-sypexdumper#1]
In Packagist I found our yii2-sypexdumper
https://packagist.org/packages/beaten-sect0r/yii2-sypexdumper
If you planed restore this package?

Thanks!

**Comment by Beaten-Sect0r** [comment]
Привет, пакет не готов и в ближайшее время не до него.

**Comment by Beaten-Sect0r** [comment]
Для своего приложения так пока накорябал - https://github.com/Beaten-Sect0r/yii2-sypexdumper
